services:
  mysql:
    image: mysql:8.0
    container_name: cpalma_mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: muebles_cpalma_db
      MYSQL_USER: dev_cpalma_user
      MYSQL_PASSWORD: dev_secure_password_2026
    volumes:
      # Esta línea es la que falta. 
      # Mapea tu script local a la carpeta de inicialización automática de MySQL
      - ./init-db:/docker-entrypoint-initdb.d